name: hiky
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  # External Packages Starts from here 
  
  # for Google fonts
  google_fonts: ^6.2.1
  # for State management
  get: ^4.6.6
  # for All screen devices
  flutter_screenutil: ^5.9.0
  # for flutter native splash 
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  lottie: ^3.1.0
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  country_code_picker: ^3.0.0
  # 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true
  assets:
   - assets/