// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgyBlwh37qPq0pm7WFswQ0ONbrO51hsaQ',
    appId: '1:65453742835:web:1b327478ad26fdd32af586',
    messagingSenderId: '65453742835',
    projectId: 'hikiy-d1335',
    authDomain: 'hikiy-d1335.firebaseapp.com',
    storageBucket: 'hikiy-d1335.appspot.com',
    measurementId: 'G-SDNREQQE3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk2zXFhfZ_8z_AQiFuu5KC3pybGNR9M-U',
    appId: '1:65453742835:android:2035a182988f04a62af586',
    messagingSenderId: '65453742835',
    projectId: 'hikiy-d1335',
    storageBucket: 'hikiy-d1335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzoNxLURDB0rpzE-n0ay6yMBFkqF30Wyo',
    appId: '1:65453742835:ios:e1945733c53f6fd02af586',
    messagingSenderId: '65453742835',
    projectId: 'hikiy-d1335',
    storageBucket: 'hikiy-d1335.appspot.com',
    iosBundleId: 'com.example.hiky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzoNxLURDB0rpzE-n0ay6yMBFkqF30Wyo',
    appId: '1:65453742835:ios:e1945733c53f6fd02af586',
    messagingSenderId: '65453742835',
    projectId: 'hikiy-d1335',
    storageBucket: 'hikiy-d1335.appspot.com',
    iosBundleId: 'com.example.hiky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgyBlwh37qPq0pm7WFswQ0ONbrO51hsaQ',
    appId: '1:65453742835:web:2cc643133ff5917d2af586',
    messagingSenderId: '65453742835',
    projectId: 'hikiy-d1335',
    authDomain: 'hikiy-d1335.firebaseapp.com',
    storageBucket: 'hikiy-d1335.appspot.com',
    measurementId: 'G-E5L8P8PGTR',
  );
}
